baseurl      = "localhost"
title        = "Arnavdeep's portfolio"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "This is my portfolio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "My portfolio website"
  keywords = "homepage, blog"
  images = [""]

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

#Social Icons

[[params.social]]
    name = "email"
    url  = "mailto:arneja.arnavsingh@gmail.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/arneja-arnav"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/arnavdeepsingh/"

[languages.en]
    title = "Hi. I'm Arnavdeep Singh"
    subtitle = "Arnavdeep's Portfolio"
    keywords = ""
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Arnavdeep's Portfolio"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
    [[menu.main]]
      identifier = "about"
      name       = "About me"
      url        = "/about"

    [[menu.main]]
      identifier = "CV"
      name       = "Curriculum Vitae"
      url        = "https://drive.google.com/file/d/1h_FG_EZXGmXehTeRVErhE-jkh6ZBfS4b/view"




