baseURL = 'https://arneja-arnav.github.io/'
languageCode = 'en-us'
title = 'Arnavdeep Singh Portfolio Website'
theme = 'hello-friend-ng'
paginate= 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "This is my personal portfolio"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  socialLinks = [
    { name = "github", url = "https://github.com/arneja-arnav" },
    { name = "twitter", url = "https://twitter.com/navcase" },
    { name = "linkedin", url = "https://www.linkedin.com/in/yourusername/" }
  ]

[taxonomies]
    category = "Blog"
    tag      = "tags"
    series   = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]

    

[languages]
  [languages.en]
    title = "This is Arnavdeep"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "This is Arnavdeep"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
  name = "About"
  URL = "/about"

  [[menu.main]]
  name = "Blog"
  URL = "/blog"

  [[menu.main]]
  name = "CV"
  URL = "https://drive.google.com/file/d/1h_FG_EZXGmXehTeRVErhE-jkh6ZBfS4b/view?usp=sharing"

  [[menu.main]]
  name = "Contact"
  URL = "/contact"
    